name: CI
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run Tests
        run: |
          python -m pip install tox
          tox
      - name: Build Coverage Report
        run: |
          python -m pip install coverage
          coverage xml -o coverage.xml
      - name: Publish Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
